TARGETS=$(wildcard *.*)

all:
	@(for t in $(TARGETS); do $(MAKE) -C $$t $@; done)

re:
	@(for t in $(TARGETS); do $(MAKE) -C $$t $@; done)

clean:
	@(for t in $(TARGETS); do $(MAKE) -C $$t $@; done)

magic:
	@(for t in $(TARGETS); do $(MAKE) -C $$t $@; done)
